BUILD: ssl: strchr definition changed in C23
New gcc and clang versions from fedora rawhide seems to use the C23
standard by default. This version changes the definition of some
string.h functions, which now return a const char * instead of a char *.

src/ssl_sock.c: In function ‘SSL_CTX_keylog’:
src/ssl_sock.c:4475:17: error: assignment discards ‘const’ qualifier from pointer target type [-Werror=discarded-qualifiers]
 4475 |         lastarg = strrchr(line, ' ');

Strangely, -Wdiscarded-qualifiers does not seem to catch all the
strrchr.

Should fix issue #3228.

This could be backported in previous versions.

(cherry picked from commit 5322bd3785353194afb384c18e1f92cffd52f613)
Signed-off-by: Christopher Faulet <cfaulet@haproxy.com>
(cherry picked from commit 5f7a6ab2ae86390a895d04f3e760b179b45dcf0b)
Signed-off-by: Christopher Faulet <cfaulet@haproxy.com>
(cherry picked from commit 6cdb6d696b73d76298188ed903ae6412b65038f1)
Signed-off-by: Christopher Faulet <cfaulet@haproxy.com>
(cherry picked from commit ed3a11ef5460be0d676585a45d41a079c834141a)
Signed-off-by: Christopher Faulet <cfaulet@haproxy.com>