BUG/MINOR: backend: fix access on shared counters array
Counters shared.tg has changed between versions. In 3.3, it is a static
array of 64 members. It has been converted so that it is dynamically
allocated in 3.4.

Thus, testing shared.tg is unnecessary on 3.3 as it is always valid.
This patch fixes the test with proper array index.

This issue has been detected while using clang compiler :

  CC      src/backend.o
src/backend.c:585:81: error: address of array 'prev->counters.shared.tg' will always evaluate to 'true' [-Werror,-Wpointer-bool-conversion]
  585 |                         else if (wcurr == wprev && curr->counters.shared.tg && prev->counters.shared.tg) {
      |                                                                             ~~ ~~~~~~~~~~~~~~~~~~~~~~^~
src/backend.c:585:53: error: address of array 'curr->counters.shared.tg' will always evaluate to 'true' [-Werror,-Wpointer-bool-conversion]
  585 |                         else if (wcurr == wprev && curr->counters.shared.tg && prev->counters.shared.tg) {
      |                                                 ~~ ~~~~~~~~~~~~~~~~~~~~~~^~
2 errors generated.
make: *** [Makefile:1062: src/backend.o] Error 1

No need to backport.