BUILD: 51d.c: cleanup, fix preprocessor ifdefs
The ifdef spans over function boundaries, making some combinations produce
code that does not build:

addons/51degrees/51d.c:638:1: error: Unmatched '}'. Configuration: ''. [syntaxError]

(cherry picked from commit 61aa17aec83ba9f333b6753e31ab9979c0752175)
Signed-off-by: Christopher Faulet <cfaulet@haproxy.com>