BUILD: quic: 32-bits compilation issue with %zu in quic_rx_pkts_del()
This issue arrived with this commit:
    1dbeb35f8 MINOR: quic: Add new traces about by connection RX buffer handling

and revealed by the GH CI as follows:

   src/quic_conn.c: In function âquic_rx_pkts_delâ:
    include/haproxy/trace.h:134:65: error: format â%zuâ expects argument of type âsize_tâ,
    but argument 6 has type âuint64_tâ {aka âlong long unsigned intâ} [-Werror=format=]
    _msg_len = snprintf(_msg, sizeof(_msg), (fmt), ##args);

Replace all %zu printf integer format by %llu.

Must be backported to 2.7 where the previous is supposed to be backported.

(cherry picked from commit b7a13be6cd20b3840ae516fc423bae27576314da)
Signed-off-by: Christopher Faulet <cfaulet@haproxy.com>