BUILD: ssl-ckch: Fix GCC warning about a if statement always true
GCC 12.2.1 reports the following error:

src/ssl_ckch.c: In function ‘ckchs_dup’:
src/ssl_ckch.c:805:29: error: the comparison will always evaluate as ‘true’ for the pointer operand in ‘src->ckch + (sizetype)((long unsigned int)n * 56)’ must not be NULL [-Werror=address]
  805 |                         if (&src->ckch[n]) {
      |                             ^

And indeed, the pointer cannot be NULL. Thus, the if statement is removed.

It is a 2.2-specific patch. There is no commit ID and no backport is needed.