BUILD: cfgparse: Fix GCC warning about a variable used after realloc
GCC 12.2.1 reports the following error;

src/cfgparse.c: In function ‘readcfgfile’:
src/cfgparse.c:2122:72: error: pointer ‘thisline’ may be used after ‘realloc’ [-Werror=use-after-free]
 2122 |                                                         diff = args[i] - thisline;
      |                                                                ~~~~~~~~^~~~~~~~~~
src/cfgparse.c:2110:51: note: call to ‘realloc’ here
 2110 |                                         newline = realloc(thisline, newlinesize * sizeof(*thisline));
      |                                                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/cfgparse.c:2130:61: error: pointer ‘thisline’ may be used after ‘realloc’ [-Werror=use-after-free]
 2130 |                                                 diff = line - thisline;
      |                                                        ~~~~~^~~~~~~~~~
src/cfgparse.c:2110:51: note: call to ‘realloc’ here
 2110 |                                         newline = realloc(thisline, newlinesize * sizeof(*thisline));
      |                                                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/cfgparse.c:2128:60: error: pointer ‘thisline’ may be used after ‘realloc’ [-Werror=use-after-free]
 2128 |                                                 diff = end - thisline;
      |                                                        ~~~~^~~~~~~~~~
src/cfgparse.c:2110:51: note: call to ‘realloc’ here
 2110 |                                         newline = realloc(thisline, newlinesize * sizeof(*thisline));
      |                                                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/cfgparse.c:2126:64: error: pointer ‘thisline’ may be used after ‘realloc’ [-Werror=use-after-free]
 2126 |                                                 diff = var_end - thisline;
      |                                                        ~~~~~~~~^~~~~~~~~~
src/cfgparse.c:2110:51: note: call to ‘realloc’ here
 2110 |                                         newline = realloc(thisline, newlinesize * sizeof(*thisline));
      |                                                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

It is apparently safe bug GCC is not agree. Thus, thisline address is saved
in a uintptr_t variable to perform all offset calculation. This way, GCC is
happy.

It is a 2.0-specific patch. Thus there is no upstream ID.