BUILD: quic: Wrong HKDF label constant variable initializations
Non constant expressions were used to initialize constant variables leading to
such compilation errors:
	src/xprt_quic.c:66:3: error: initializer element is not a constant expression
   .key_label_len    = strlen(QUIC_HKDF_KEY_LABEL_V1),
Reproduced with CC=gcc-4.9 compilation option.
Fix using macros for each HKDF label.

(cherry picked from commit b1cb95858112880adcaa3aa0e2e6809a537a71c8)
Signed-off-by: Willy Tarreau <w@1wt.eu>