BUILD: acme: fix false positive null pointer dereference
src/acme.c: In function âcfg_parse_acme_vars_providerâ:
src/acme.c:471:9: error: potential null pointer dereference [-Werror=null-dereference]
  471 |         free(*dst);
      |         ^~~~~~~~~~

gcc13 on ubuntu 24.04 detects a false positive when building
3e72a9f ("MINOR: acme: provider-name for dpapi sink").
Indeed dst can't be NULL. Clarify the code so gcc don't complain
anymore.

(cherry picked from commit b3b910cc3f342a5e86c79859d223efeafc61d53d)
[wt: keeping acme up-to-date with 3.3]
Signed-off-by: Willy Tarreau <w@1wt.eu>