BUILD: http-htx: Silent build error about a possible NULL start-line
In http_replace_req_uri(), if the URI was successfully replaced, it means
the start-line exists. However, the compiler reports an error about a
possible NULL pointer dereference:

src/http_htx.c: In function ‘http_replace_req_uri’:
src/http_htx.c:392:19: error: potential null pointer dereference [-Werror=null-dereference]
  392 |         sl->flags &= ~HTX_SL_F_NORMALIZED_URI;

So, ALREADY_CHECKED() macro is used to silent the build error. This patch
must be backported with 84cdbe478a ("BUG/MINOR: http-htx: Don't consider an
URI as normalized after a set-uri action").

(cherry picked from commit 92c2de1a06a5d2be4f498503fa09372256339c8b)
Signed-off-by: Christopher Faulet <cfaulet@haproxy.com>
(cherry picked from commit 9d7b6975f7ce71e4ba95768f6ce8da0e780724bf)
Signed-off-by: Christopher Faulet <cfaulet@haproxy.com>
(cherry picked from commit b2aff14bae82dc78c909800922164de96845ebc6)
Signed-off-by: Christopher Faulet <cfaulet@haproxy.com>