BUG/MINOR: ech: fix label at end of compound statement
The "ignore_entry" label used to skip non ".ech" directory entries in
load_echkeys() was placed right before the closing brace of the "for"
loop, with no statement attached to it. A label with no following
statement is only valid since C23, so strict compilers reject it:

  src/ech.c:96:2: error: label at end of compound statement is a C23
  extension [-Werror,-Wc23-extensions]

Add a null statement after the label.

(cherry picked from commit dcc1b7f9b61187f79af7940d0f5954586122c44d)
Signed-off-by: William Lallemand <wlallemand@haproxy.com>
(cherry picked from commit e7d2800db4b92e3337fa7bc353f008c8ace626c6)
Signed-off-by: William Lallemand <wlallemand@haproxy.com>